feat/from2
tutuka00/testBD pull request #2
Opened 2023-10-19 13:02 UTC by tutuka00

2023-10-19 23:44 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-10-19 23:44 UTC, KatsuyaTanaka95 commented on src/app/SpendingDataFetcher.php
> +    }
今回も素晴らしいですね！！！
練習として、
ここのコードを「SpendingCalculator.php」ファイルに書いて使うようにしてみましょう！

Spendingテーブルのデータをあつかうものに関しては、今回は、「SpendingCalculator.php」ファイルにまとめていくようにしましょう！！！😊

2023-10-22 01:23 UTC, tutuka00 commented on src/app/SpendingDataFetcher.php
> +    }
かしこまりました！
ありがとうございます！Spendingテーブルを使う時は「SpendingCalculator.php」
ファイルに都度都度、追記していくような形という事でよろしいでしょうか？

2023-10-23 05:07 UTC, KatsuyaTanaka95 commented on src/app/SpendingDataFetcher.php
> +    }
ご確認ありがとうございます！
その認識で問題ございません！！
Spendingテーブルを使う時は「SpendingCalculator.php」
ファイルに都度都度、追記していってください！！😊

2023-10-23 05:09 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2023-10-24 14:31 UTC, merged